cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.pay, name="home"),
    url(r'^done/$', views.payment_done, name="done"),
    url(r'^canceled/$', views.payment_canceled, name="canceled"),

]

physioboost/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from account import views as do_login
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^leagues/', include('leagues.urls')),
    url(r'^clubs/', include('clubs.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^injuries/', include('injuries.urls')),
    url(r'^assessment/', include('assessment.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^status/', include('status.urls')),
    url(r'^about/$', views.about),
    url(r'^$', do_login.login_view, name="home"),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name='account/reset-password.html'), name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='account/reset-password-done.html'), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z].+)/$', PasswordResetConfirmView.as_view(template_name='account/reset-password-confirm.html'), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='account/reset-password-complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

players/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'players'

urlpatterns = [
    url(r'^view/$', views.view_player, name="view"),
    url(r'^profile/(?P<slug>[\w-]+)/$', views.view_profile, name="profile"),
    url(r'^add/$', views.add_player, name="add_player"),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.edit_player, name="edit_player"),
    url(r'^delete/(?P<id>[\w-]+)/$', views.delete_player, name="delete_player"),

]

players/models.py
from django.db import models
from clubs.models import Club
from status.models import Status
from foot.models import Foot
from position.models import Position
import re
from django.template.defaultfilters import slugify
from django.utils.text import slugify
from random import randint
from datetime import date            

# Create your models here.
STATUS = 2
class Player(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100, default=None)
    address = models.CharField(max_length=200, default=None)
    date_of_birth = models.DateField(null=True, default=None)
    age = models.PositiveIntegerField(null=True, default=None)
    height = models.DecimalField(decimal_places=2, max_digits=3, default=None)
    weight = models.DecimalField(decimal_places=2, max_digits=5, default=None)
    club = models.ForeignKey(Club, on_delete=models.DO_NOTHING, default=None)
    preferred_foot = models.ForeignKey(Foot, on_delete = models.DO_NOTHING, default=None)
    position = models.ForeignKey(Position, on_delete = models.DO_NOTHING, default=None)
    jersey_number = models.PositiveIntegerField(null=True, default=None)
    strengths = models.CharField(max_length=100, default=None)
    weaknesses = models.CharField(max_length=100, default=None)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING, default=STATUS, null=False)
    image = models.ImageField(default='default.png', blank=True)
    slug = models.SlugField(default=None, unique=True)
    
    def __str__(self):
        return self.name

    def __str__(self):
        return self.surname

    def save(self, *args, **kwargs):
        if self.slug:
            origname = Player.objects.get(slug=self.slug).name
            origsurname = Player.objects.get(slug=self.slug).surname
            if self.name == origname:
                if self.surname == origsurname:
                    super(Player, self).save(*args, **kwargs)
                elif Player.objects.filter(name=self.name).exists() & Player.objects.filter(surname=self.surname).exists():
                    extra = str(randint(1,10))
                    self.slug = slugify(str('%s %s' % (self.name, self.surname))) + "-" + extra
                    super(Player, self).save(*args, **kwargs)
        else:
            if Player.objects.filter(name=self.name).exists() & Player.objects.filter(surname=self.surname).exists():
                extra = str(randint(1,10))
                self.slug = slugify(str('%s %s' % (self.name, self.surname))) + "-" + extra
                super(Player, self).save(*args, **kwargs)

            else:
                self.slug = slugify(str('%s %s' % (self.name, self.surname)))
                super(Player, self).save(*args, **kwargs)


        if self.date_of_birth:
            def calculate_age(born):
                today = date.today()
                return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

            self.age = calculate_age(self.date_of_birth)
            super(Player, self).save(*args, **kwargs)

        

players/forms.py
from django import forms
from . import models

class AddPlayer(forms.ModelForm):
    class Meta:
        model = models.Player
        fields = ['name', 'surname', 'date_of_birth', 'nationality', 'address','height', 'weight', 'preferred_foot', 'position', 'jersey_number', 'strengths', 'weaknesses', 'club', 'image']

        widgets = {
            'name' : forms.TextInput(attrs={'id': 'first_name', 'class': 'validate'}),
            'surname' : forms.TextInput(attrs={'id': 'last_name', 'class': 'validate'}),
            'date_of_birth' : forms.TextInput(attrs={'id': 'date', 'class': 'datepicker'}),
            'nationality' : forms.TextInput(attrs={'id': 'nationality', 'class': 'validate'}),
            'address' : forms.TextInput(attrs={'id': 'address', 'class': 'validate'}),
            'height' : forms.NumberInput(attrs={'id': 'height', 'class': 'validate'}),
            'weight' : forms.NumberInput(attrs={'id': 'weight', 'class': 'validate'}),
            'preferred_foot' : forms.Select(attrs={'id': 'preferred_foot', 'class': 'validate'}),
            'position' : forms.Select(attrs={'id': 'position', 'class': 'validate'}),
            'jersey_number' : forms.NumberInput(attrs={'id': 'jersey_number', 'class': 'validate'}),
            'strengths' : forms.TextInput(attrs={'id': 'strengths', 'class': 'validate'}),
            'weaknesses' : forms.TextInput(attrs={'id': 'weaknesses', 'class': 'validate'}),
            'club' : forms.Select(attrs={'id': 'club', 'class': 'validate'}),
            'image' : forms.FileInput(attrs={'id': 'image','type' :'file', 'class' : 'dropify', 'data-height':'100'}),
        }

class EditStatus(forms.ModelForm):
    class Meta:
        model = models.Player
        fields = ['status']

players/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core import serializers
from players.models import Player
from stats.models import Stats
from django.contrib.auth.decorators import login_required
from . import forms
from django.shortcuts import get_object_or_404
from .decorators import admin_required
from django.db.models import Sum


# Create your views here.
@login_required(login_url="/account/login/")
def view_player(request):
    players = Player.objects.all() #or any kind of queryset
    return render(request, 'players/view_players.html', {'players':players})

@login_required(login_url="/account/login/")
def view_profile(request, slug):
    player_id = Player.objects.get(slug=slug).id
    #stats = Stats.objects.filter(player_id=player_id)
    #stats = Stats.objects.values('player_id', 'club_id','season').annotate(dgoals=Sum('goals'), dassists=Sum('assists')).filter(player_id=player_id)
    stats = Stats.objects.raw("SELECT 1 as id, SUM(goals) as dgoals, SUM(assists) as dassists, clubs_club.name as clubname, clubs_club.image as clubimage, club_id, season_id FROM  stats_stats LEFT JOIN clubs_club ON stats_stats.club_id=clubs_club.id WHERE player_id=%s GROUP BY club_id, season_id ORDER BY season_id DESC", [player_id])
    players = Player.objects.get(slug=slug) #or any kind of queryset
    context = {'player':players, 'stats':stats}
    return render(request, 'players/profile.html', context=context)

@login_required(login_url="/account/login/")
@admin_required
def add_player(request):
    if request.method == 'POST':
        form = forms.AddPlayer(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            messages.success(request, 'Player added successfully!!!')
            return redirect('players:add_player')
        else:
            messages.warning(request, 'Please correct the error below.') 
    else:
        form = forms.AddPlayer()
    return render(request, 'players/add_player.html', {'form':form})

@login_required(login_url="/account/login/")
@admin_required
def edit_player(request, slug):
    players = Player.objects.get(slug=slug)
    form = forms.AddPlayer(instance=players)
    if request.method == 'POST':
        form = forms.AddPlayer(request.POST,request.FILES, instance=players)
        if form.is_valid():
            form.save()
            messages.success(request, 'Player information changed successfully!!!')
        else:
            messages.warning(request, 'Please correct the error below.') 
    return render(request, 'players/edit_player.html', {'form':form})

@login_required(login_url="/account/login/")
@admin_required
def delete_player(request, id):
    p = Player.objects.get(pk=id)
    p.delete()
    messages.warning(request, 'Player deleted!!!')
    return redirect('players:view')

players/templates/players/add_player.html
{% extends 'base_layout.html' %}

{% block content %}
<title>PhysioBoost Admin: Add Player </title>
<section id="content">

    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Add Player</h5>
            <ol class="breadcrumbs">
              <li><a href="index.html">Dashboard</a>
              </li>
              <li><a href="#">Players</a>
              </li>
              <li class="active">Add Player</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--start container-->
    <div class="container">
      <div class="section">
        <!--Input fields-->
        <div id="input-fields">
          <div class="row">
            <div class="col s12 m8 l12">
              <div class="row">
                <form class="col s12" action="{% url 'players:add_player' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.name }}
                      <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.surname }}
                      <label for="last_name">Last Name</label>
                    </div>
                  </div><br>
                  
                  <div class="row">
                    <div id="input-date-picker" class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.date_of_birth }}
                        <label for="input-date-picker">Date of Birth</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.nationality }}
                      <label for="nationality">Nationality</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.address }}
                        <label for="address">Address</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.height }}
                      <label for="height">Height</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.weight }}
                        <label for="weight">Weight</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        <div class="select-wrapper">
                            {{ form.preferred_foot }}
                            <label class="label-wrapper" for="preferred_foot">Preferred Foot</label>
                        </div>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        <div class="select-wrapper">
                            {{ form.position }}
                            <label class="label-wrapper" for="position">Position</label>
                        </div>
                    </div>

                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.jersey_number }}
                        <label for="jersey_number">Jersey Number</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.strengths }}
                      <label for="strengths">Strengths</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.weaknesses }}
                      <label for="weaknesses">Weaknesses</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        <div class="select-wrapper">
                            {{ form.club }}
                            <label class="label-wrapper" for="club">Club</label>
                        </div>
                    </div>
                 </div>
                 <div class="row">
                    <div class="input-field col s12">
                      <p>Upload an Image</p>
                      {{ form.image }}
                      {{ form.image.errors }}
                    </div>
                </div><br>

                  <div class="center">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Add Player</button>
                  </div><br>
                </form>
              </div>
            </div>
          </div>
        </div>
</div>
<!--end container-->

</section>
<!-- END CONTENT -->

{% endblock %}

players/templates/players/edit_player.html
{% extends 'base_layout.html' %}

{% block content %}
<title>PhysioBoost Admin: Edit Player </title>
<section id="content">

    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Edit Player</h5>
            <ol class="breadcrumbs">
              <li><a href="index.html">Dashboard</a>
              </li>
              <li><a href="#">Players</a>
              </li>
              <li class="active">Edit Player</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--start container-->
    <div class="container">
      <div class="section">
        <!--Input fields-->
        <div id="input-fields">
          <div class="row">
            <div class="col s12 m8 l12">
              <div class="row">
                <form class="col s12" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.name }}
                      <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.surname }}
                      <label for="last_name">Last Name</label>
                    </div>
                  </div><br>
                  
                  <div class="row">
                    <div id="input-date-picker" class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.date_of_birth }}
                        <label for="input-date-picker">Date of Birth</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.nationality }}
                      <label for="nationality">Nationality</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.address }}
                        <label for="address">Address</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.height }}
                      <label for="height">Height</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.weight }}
                        <label for="weight">Weight</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        <div class="select-wrapper">
                            {{ form.preferred_foot }}
                            <label class="label-wrapper" for="preferred_foot">Preferred Foot</label>
                        </div>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        <div class="select-wrapper">
                            {{ form.position }}
                            <label class="label-wrapper" for="position">Position</label>
                        </div>
                    </div>

                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.jersey_number }}
                        <label for="jersey_number">Jersey Number</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.strengths }}
                      <label for="strengths">Strengths</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.weaknesses }}
                      <label for="weaknesses">Weaknesses</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        <div class="select-wrapper">
                            {{ form.club }}
                            <label class="label-wrapper" for="club">Club</label>
                        </div>
                    </div>
                    <div class="row">
                      <div class="input-field col s12">
                        <p>Upload an Image</p>
                        {{ form.image }}
                        {{ form.image.errors }}
                    </div>
                 </div><br>
                  <div class="center">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Edit Player</button>
                  </div><br>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="divider"></div>
        <!-- Floating Action Button -->
</div>
<!--end container-->

</section>
<!-- END CONTENT -->

{% endblock %}

players/templates/players/view_players.html
{% extends 'base_layout.html' %}

{% block content %}

<title>PhysioBoost: View Players</title>
 <!-- START CONTENT -->
 <section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">View Players</h5>
            <ol class="breadcrumbs">
                <li><a href="index.html">Dashboard</a></li>
                <li><a href="#">Players</a></li>
                <li class="active">View Players</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
    

    <!--start container-->
    <div class="container">
      <div class="section">
        <!--DataTables example-->
        <div id="table-datatables">
          <div class="row">
            
            <div class="col s12 m8 l12">
              <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name & Surname</th>
                        <th>Age</th>
                        <th>Club</th>
                        <th>Height</th>
                        <th>Weight</th>
                        <th>Preferred Foot</th>
                        <th>Position</th>
                        <th>Jersey Number</th>
                        <th>Status</th>
                        {% if user.is_authenticated and user.is_admin %}
                        <th>Action</th>
                        {% endif %}
                    </tr>
                </thead>
             
                <tbody>
                    {% for player in players %}
                    <tr>
                        <td><a href="{% url 'players:profile' slug=player.slug %}">{{ player.name}} {{player.surname}}</a></td>
                        <td>{{ player.age }}</td>
                        <td>{{ player.club }}</td>
                        <td>{{ player.height }}</td>
                        <td>{{ player.weight }}</td>
                        <td>{{ player.preferred_foot }}</td>
                        <td>{{ player.position }}</td>
                        <td>{{ player.jersey_number }}</td>
                        <td>{{ player.status }}</td>
                        {% if user.is_authenticated and user.is_admin %}
                        <td><a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit Player" href="{% url 'players:edit_player' slug=player.slug %}"><i class="mdi-image-edit"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Delete Player" onclick="return confirm('Are you sure you want to delete this player? This action cannot be undone');" href="{% url 'players:delete_player' id=player.id %}"><i class="mdi-action-delete"></i></a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div> 
        <br>
      </div>
      <!-- Floating Action Button -->
        <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
            <a class="btn-floating btn-large">
              <i class="mdi-action-stars"></i>
            </a>
            <ul>
              <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
              <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
              <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
              <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
            </ul>
        </div>
        <!-- Floating Action Button -->
        
    </div>
    <!--end container-->

  </section>
  <!-- END CONTENT -->
{% endblock %}