assessment/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'assessment'

urlpatterns = [
    url(r'^$', views.assess, name="view_assess"),
    url(r'^players/$', views.player_assessment, name="player_assessment"),
    url(r'^assess/(?P<slug>[\w-]+)/$', views.add_assessment, name="add_assessment"),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.edit_assessment, name="edit_assessment"),
    url(r'^view/(?P<id>[\w-]+)/$', views.single_assessment, name="single_assessment"),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.pay, name="home"),
    url(r'^done/$', views.payment_done, name="done"),
    url(r'^canceled/$', views.payment_canceled, name="canceled"),

]

physioboost/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from account import views as do_login
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^leagues/', include('leagues.urls')),
    url(r'^clubs/', include('clubs.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^injuries/', include('injuries.urls')),
    url(r'^assessment/', include('assessment.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^status/', include('status.urls')),
    url(r'^about/$', views.about),
    url(r'^$', do_login.login_view, name="home"),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name='account/reset-password.html'), name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='account/reset-password-done.html'), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z].+)/$', PasswordResetConfirmView.as_view(template_name='account/reset-password-confirm.html'), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='account/reset-password-complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assessment/models.py
from django.db import models
from players.models import Player
from injuries.models import Injuries
from bodyparts.models import BodyParts
from injurytype.models import InjuryType
from injurycause.models import InjuryCause
from injuryoccur.models import InjuryOccur
from injuryco.models import InjuryCo
from injuryviolation.models import InjuryViolation
from advicegiven.models import AdviceGiven
from diagnosis.models import Diagnosis
from severity.models import Severity
from actiontaken.models import ActionTaken
from injuryprevious.models import InjuryPrevious
from refereesanction.models import RefereeSanction
from referral.models import Referral
from protective_equipment.models  import ProtectiveEquipment
from django.conf import settings
User = settings.AUTH_USER_MODEL

# Create your models here.
class Assessment(models.Model):
    name = models.CharField(max_length=100, default=None, null=True)
    surname = models.CharField(max_length=100, default=None, null=True)
    injured_body_parts = models.ManyToManyField(BodyParts)
    injury_type = models.ManyToManyField(InjuryType)
    other_injury = models.CharField(max_length=100, default=None, null=True)
    diagnosis = models.CharField(max_length=100, default=None, null=True)
    injury_previous = models.ManyToManyField(InjuryPrevious)
    injury_cause = models.ManyToManyField(InjuryCause)
    injury_occur = models.ManyToManyField(InjuryOccur)
    injury_occur_other = models.CharField(max_length=100, default=None, null=True)
    injury_co = models.ManyToManyField(InjuryCo)
    other_collision =  models.CharField(max_length=100, default=None, null=True)
    injury_violation = models.ManyToManyField(InjuryViolation)
    referee_sanction = models.ManyToManyField(RefereeSanction)
    advice_given = models.ManyToManyField(AdviceGiven)
    other_advice_given = models.CharField(max_length=100, default=None, null=True)
    severity = models.ManyToManyField(Severity)
    action_taken = models.ManyToManyField(ActionTaken)
    referral = models.ManyToManyField(Referral)
    other_referral = models.CharField(max_length=100, default=None, null=True)
    protective_equipment = models.ManyToManyField(ProtectiveEquipment)
    other_protective_equipment = models.CharField(max_length=100, default=None, null=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=18)
    
    def __str__(self):
        return self.name + " " + self.surname

    
    

assessment/forms.py
from django import forms
from . import models
from bodyparts.models import BodyParts
from injurytype.models import InjuryType
from injurycause.models import InjuryCause
from injuryoccur.models import InjuryOccur
from injuryco.models import InjuryCo
from injuryviolation.models import InjuryViolation
from advicegiven.models import AdviceGiven
from severity.models import Severity
from actiontaken.models import ActionTaken
from injuryprevious.models import InjuryPrevious
from refereesanction.models import RefereeSanction
from referral.models import Referral
from protective_equipment.models  import ProtectiveEquipment

class AddAssessment(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddAssessment, self).__init__(*args, **kwargs)
    class Meta:
        model = models.Assessment
        fields = ['injured_body_parts', 'injury_type', 'other_injury', 'diagnosis', 'injury_cause', 'injury_occur', 'injury_co','injury_violation', 'advice_given', 'severity', 'action_taken', 'injury_previous', 'other_collision', 'referee_sanction', 'injury_occur_other', 'other_advice_given', 'referral','other_referral', 'protective_equipment', 'other_protective_equipment']

        widgets = {
            'other_injury' : forms.TextInput(attrs={'id': 'other_injury', 'class': 'validate'}),
        }


    injured_body_parts = forms.ModelMultipleChoiceField(
        queryset=BodyParts.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    injury_type = forms.ModelMultipleChoiceField(
        queryset=InjuryType.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    injury_cause = forms.ModelMultipleChoiceField(
        queryset=InjuryCause.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    injury_occur = forms.ModelMultipleChoiceField(
        queryset=InjuryOccur.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    injury_co = forms.ModelMultipleChoiceField(
        queryset=InjuryCo.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    injury_violation = forms.ModelMultipleChoiceField(
        queryset=InjuryViolation.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    advice_given = forms.ModelMultipleChoiceField(
        queryset=AdviceGiven.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    severity = forms.ModelMultipleChoiceField(
        queryset=Severity.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    action_taken = forms.ModelMultipleChoiceField(
        queryset=ActionTaken.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    injury_previous = forms.ModelMultipleChoiceField(
        queryset=InjuryPrevious.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    referee_sanction = forms.ModelMultipleChoiceField(
        queryset=RefereeSanction.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    referral = forms.ModelMultipleChoiceField(
        queryset=Referral.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    protective_equipment = forms.ModelMultipleChoiceField(
        queryset=ProtectiveEquipment.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )











        

assessment/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from . import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . models import Assessment
from players.models import Player
from dataset.models import Dataset
from .decorators import admin_required
from diagnosis.models import Diagnosis

@login_required(login_url="/account/login/")
def assess(request):
    assessments = Assessment.objects.all()
    return render(request, 'assessment/view_assessment.html', {'assessments':assessments})

@login_required(login_url="/account/login/")
def player_assessment(request):
    player =   Player.objects.all()
    return render(request, 'assessment/player_assessment.html', {'players':player})

@login_required(login_url="/account/login/")
def add_assessment(request, slug):
    if 'term' in request.GET:
        qs = Diagnosis.objects.filter(name__istartswith=request.GET.get('term')) | Diagnosis.objects.filter(code__istartswith=request.GET.get('term'))
        names = list()
        for name in qs:
            names.append(name.code + " - " + name.name)
        return JsonResponse(names, safe=False)
        
    player_slug = Player.objects.get(slug=slug).slug
    player_name = Player.objects.get(slug=player_slug).name
    player_surname = Player.objects.get(slug=player_slug).surname
    player_age = Player.objects.get(slug=player_slug).age
    player_weight = Player.objects.get(slug=player_slug).weight
    player_height = Player.objects.get(slug=player_slug).height
    if request.method == 'POST':
        form = forms.AddAssessment(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.name = player_name
            instance.surname = player_surname
            instance.author = request.user
            #dataset = Dataset(age=player_age, weight=player_weight, height=player_height, classification=form.cleaned_data['injury'])
            #dataset.save()
            instance.save()
            form.save_m2m()
            messages.success(request, 'Player assessed successfully!!!')
            return redirect('assessment:player_assessment')
        else:
            messages.warning(request, 'Please correct the error below.') 
    else:
        form = forms.AddAssessment()
    return render(request, 'assessment/add_assessment.html', {'form':form})

@login_required(login_url="/account/login/")
@admin_required
def edit_assessment(request, slug):
    assessment = Assessment.objects.get(id=slug)
    form = forms.AddAssessment(instance=assessment)
    if request.method == 'POST':
        form = forms.AddAssessment(request.POST, instance=assessment)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            form.save()
            messages.success(request, 'Assessment information changed successfully!!!')
        else:
            messages.warning(request, 'Please correct the error below.') 
    return render(request, 'assessment/edit_assessment.html', {'form':form})

@login_required(login_url="/account/login/")
def single_assessment(request, id):
    assessment = Assessment.objects.get(id=id)
    return render(request, 'assessment/single_assessment.html', {'assessment':assessment})

assessment/templates/assessment/add_assessment.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static from static %}
<title>Assessing Player </title>
<section id="content">
  <!--breadcrumbs start-->
  <div id="breadcrumbs-wrapper">
    <!-- Search for small screen -->
    <div class="header-search-wrapper grey hide-on-large-only">
        <i class="mdi-action-search active"></i>
        <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
    </div>
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12">
        <h5 class="breadcrumbs-title">Assess Player</h5>
        <ol class="breadcrumbs">
            <li><a href="index.html">Dashboard</a></li>
            <li><a href="#">Assessment</a></li>
            <li class="active">Assess Player</li>
        </ol>
        {% for message in messages %}
        <div id="card-alert" class="card {{ message.tags }}">
            <div class="card-content white-text">
              <p>{{ message }}</p>
            </div>
            <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
      </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
<!--breadcrumbs end-->

  <!--start container-->
  <div class="container">
    <div class="section">
      <!--Input fields-->
      <div id="input-fields">
        <div class="row">
          <div class="col s12 m12 l12">
            <div class="row">
              <form class="col s12" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <h5 class="center">ASSESSMENT</h5>
                <div class="row col l12 m12 s12">
                    <h5 class="center">Injured Body Part</h5>
                    {% for field in form.injured_body_parts %}
                    <div class="input-field col l2 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                </div><br>

                <div class="row col l12 m12 s12">
                    <h5 class="center">Injury Type</h5>
                    {% for field in form.injury_type %}
                    <div class=" input-field col l3 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                </div><br>

                <div class="row col l12 m12 s12">
                  <div class="input-field col l12 m12 s12">
                    {{ form.other_injury }}
                  <label for="other_injury">Other Injury</label>
                </div><br>

                <div class="row col l12 m12 s12">
                  <h5 class="center">Diagnosis</h5>
                  <div class="input-field col s12 m6 l12">
                    {{ form.diagnosis }}
                  <label for="other_injury">Diagnosis</label>
                </div><br>

                <div class="row col l12 m12 s12">
                    <h5 class="center">Is this injury a recurrence</h5>
                    {% for field in form.injury_previous %}
                    <div class="col l4 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                </div><br>


                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Cause of Injury</h5>
                    {% for field in form.injury_cause %}
                    <div class="col l2 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">When did the injury occur?</h5>
                    {% for field in form.injury_occur %}
                    <div class="col l2 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row col l12 m12 s12">
                  <div class="input-field col l12 m12 s12">
                    {{ form.injury_occur_other }}
                  <label for="injury_occur_other">Other</label>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Was the injury caused by contact or collision?</h5>
                    {% for field in form.injury_co %}
                    <div class="col l4 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row col l12 m12 s12">
                  <div class="input-field col l12 m12 s12">
                    {{ form.other_collision }}
                  <label for="other_injury">Yes, with other object(specify)</label>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Did the referee indicate that the action leading to the injury was a violation of the laws?</h5>
                    {% for field in form.injury_violation %}
                    <div class="col l4 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h6 class="center">If YES, who was the referee's sanction against</h6>
                    {% for field in form.referee_sanction %}
                    <div class="col l2 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Advice Given</h5>
                    {% for field in form.advice_given %}
                    <div class="col l3 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row col l12 m12 s12">
                  <div class="input-field col l12 m12 s12">
                    {{ form.other_advice_given }}
                  <label for="other_advice_given">Other</label>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Referral</h5>
                    {% for field in form.referral %}
                    <div class="col l3 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row col l12 m12 s12">
                  <div class="input-field col l12 m12 s12">
                    {{ form.other_referral }}
                  <label for="other_advice_given">Other</label>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Was protective equipment worn on the body parts?</h5>
                    {% for field in form.protective_equipment %}
                    <div class="col l4 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row col l12 m12 s12">
                  <div class="input-field col l12 m12 s12">
                    {{ form.other_protective_equipment }}
                  <label for="other_injury">If yes, what? e.g. mouth guard, brace?  </label>
                </div><br>


                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center"> Provisional Severity Assessment</h5>
                    {% for field in form.severity %}
                    <div class="col l4 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>

                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <h5 class="center">Action Taken</h5>
                    {% for field in form.action_taken %}
                    <div class="col l2 m3 s6" style="line-height: 4rem;">
                      {{ field.tag }}
                      <label for="{{ field.id_for_label }}">{{ field.choice_label }}</label>
                    </div>
                    {% endfor %}
                  </div>
                </div><br>
                <div class="center">
                  <button class="btn waves-effect waves-light" type="submit" name="action">Add Assessment</button>
                </div><br>
              </form>
            </div>
          </div>
        </div>
      </div>

      <div class="divider"></div>
      <!-- Floating Action Button -->
</div>
<!--end container-->

</section>
<!-- END CONTENT -->
<!-- END CONTENT -->

{% endblock %}

assessment/templates/assessment/player_assessment.html
{% extends 'base_layout.html' %}

{% block content %}

<title>PhysioBoost: Assess Player</title>
 <!-- START CONTENT -->
 <section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Assess Player</h5>
            <ol class="breadcrumbs">
                <li><a href="index.html">Dashboard</a></li>
                <li><a href="#">Assessment</a></li>
                <li class="active">Assess Player</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
    

    <!--start container-->
    <div class="container">
      <div class="section">
        <!--DataTables example-->
        <div id="table-datatables">
          <div class="row">
            
            <div class="col s12 m8 l12">
              <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name & Surname</th>
                        <th>Age</th>
                        <th>Club</th>
                        <th>Height</th>
                        <th>Weight</th>
                        <th>Preferred Foot</th>
                        <th>Position</th>
                        <th style="width: 5%;">Jersey Number</th>
                        <th>Status</th>
                        {% if user.is_authenticated and user.is_admin %}
                        <th>Action</th>
                        {% endif %}
                    </tr>
                </thead>
             
                <tbody>
                    {% for player in players %}
                    <tr>
                        <td>{{ player.name}} {{player.surname}}</td>
                        <td>{{ player.age }}</td>
                        <td>{{ player.club }}</td>
                        <td>{{ player.height }}</td>
                        <td>{{ player.weight }}</td>
                        <td>{{ player.preferred_foot }}</td>
                        <td>{{ player.position }}</td>
                        <td>{{ player.jersey_number }}</td>
                        <td>{{ player.status }}</td>
                        {% if user.is_authenticated and user.is_admin %}
                        <td><a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Assess Player" href="{% url 'assessment:add_assessment' slug=player.slug %}"><i class="mdi-action-assignment"></i></a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div> 
        <br>
      </div>
      <!-- Floating Action Button -->
        <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
            <a class="btn-floating btn-large">
              <i class="mdi-action-stars"></i>
            </a>
            <ul>
              <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
              <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
              <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
              <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
            </ul>
        </div>
        <!-- Floating Action Button -->
        
    </div>
    <!--end container-->

  </section>
  <!-- END CONTENT -->
{% endblock %}

assessment/templates/assessment/view_assessment.html
{% extends 'base_layout.html' %}

{% block content %}

<title>PhysioBoost: View Players</title>
 <!-- START CONTENT -->
 <section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">View Players</h5>
            <ol class="breadcrumbs">
                <li><a href="index.html">Dashboard</a></li>
                <li><a href="#">Players</a></li>
                <li class="active">View Players</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
    

    <!--start container-->
    <div class="container">
      <div class="section">
        <!--DataTables example-->
        <div id="table-datatables">
          <div class="row">
            
            <div class="col s12 m8 l12 responsive-table">
              <table id="data-table-simple" class="display">
                <thead>
                    <tr>
                        <th>Name & Surname</th>
                        <th>Complaint</th>
                        <th>History</th>
                        <th>Duration</th>
                        {% if user.is_authenticated and user.is_admin %}
                        <th>Action</th>
                        {% endif %}
                    </tr>
                </thead>
             
                <tbody>
                    {% for assessment in assessments %}
                    <tr>
                        <td><a href="{% url 'assessment:single_assessment' id=assessment.id %}">{{ assessment.name}} {{assessment.surname}}</a></td>
                        <td>{{ assessment.complaint }}</td>
                        <td>{{ assessment.history }}</td>
                        <td>{{ assessment.duration }}</td>
                        {% if user.is_authenticated and user.is_admin %}
                        <td><a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit Assessment" href="{% url 'assessment:edit_assessment' slug=assessment.id %}"><i class="mdi-image-edit"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div> 
        <br>
      </div>
      <!-- Floating Action Button -->
        <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
            <a class="btn-floating btn-large">
              <i class="mdi-action-stars"></i>
            </a>
            <ul>
              <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
              <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
              <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
              <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
            </ul>
        </div>
        <!-- Floating Action Button -->
        
    </div>
    <!--end container-->

  </section>
  <!-- END CONTENT -->
{% endblock %}