cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.pay, name="home"),
    url(r'^done/$', views.payment_done, name="done"),
    url(r'^canceled/$', views.payment_canceled, name="canceled"),

]

injuries/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'injuries'

urlpatterns = [
    url(r'^$', views.injury_view, name="view_injuries"),
    url(r'^view/(?P<slug>[\w-]+)/$', views.single_injuries, name="single_injuries"),
    url(r'^add/$', views.add_injuries, name="add_injury"),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.edit_injury, name="edit_injuries"),
    url(r'^delete/(?P<id>[\w-]+)/$', views.delete_injury, name="delete_injuries"),
    url(r'^players/$', views.view_players, name="view_players"),
    url(r'^predict/(?P<slug>[\w-]+)/$', views.predict_injury, name="predict_injury"),
    
    
]

physioboost/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from account import views as do_login
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^leagues/', include('leagues.urls')),
    url(r'^clubs/', include('clubs.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^injuries/', include('injuries.urls')),
    url(r'^assessment/', include('assessment.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^status/', include('status.urls')),
    url(r'^about/$', views.about),
    url(r'^$', do_login.login_view, name="home"),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name='account/reset-password.html'), name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='account/reset-password-done.html'), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z].+)/$', PasswordResetConfirmView.as_view(template_name='account/reset-password-confirm.html'), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='account/reset-password-complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

players/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'players'

urlpatterns = [
    url(r'^view/$', views.view_player, name="view"),
    url(r'^profile/(?P<slug>[\w-]+)/$', views.view_profile, name="profile"),
    url(r'^add/$', views.add_player, name="add_player"),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.edit_player, name="edit_player"),
    url(r'^delete/(?P<id>[\w-]+)/$', views.delete_player, name="delete_player"),

]

injuries/models.py
from django.db import models
from django.contrib.auth.models import User
from severity.models import Severity
from django.template.defaultfilters import slugify
from django.utils.text import slugify
from random import randint

# Create your models here.
class Injuries(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    symptoms = models.TextField(max_length=500)
    diagnostic_tests = models.TextField(max_length=500)
    classification = models.ForeignKey(Severity, max_length=500, on_delete=models.DO_NOTHING, null=True, default=None, blank=True)
    healing = models.TextField(max_length=500)
    complications = models.TextField(max_length=500)
    treatment = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.png', blank=True)
    slug = models.SlugField(default=None, unique=True)
    
    def __str__(self):
        return self.id

    def __str__(self):
        return self.name

    def description_snippet(self):
        return self.description[:9] + '...'
    
    def symptoms_snippet(self):
        return self.symptoms[:9] + '...'

    def diag_snippet(self):
        return self.diagnostic_tests[:9] + '...'

    def healing_snippet(self):
        return self.healing[:6] + '...'

    def complications_snippet(self):
        return self.complications[:6] + '...'

    def treatment_snippet(self):
        return self.treatment[:6] + '...'
    
    def save(self, *args, **kwargs):
        if Injuries.objects.filter(name=self.name).exists():
            extra = str(randint(1,10))
            self.slug = slugify(self.name) + "-" + extra
        else:
            self.slug = slugify(self.name)
        super(Injuries, self).save(*args, **kwargs)



    def save(self, *args, **kwargs):
        if self.slug:
            origname = Injuries.objects.get(slug=self.slug).name
            if self.name == origname:
                super(Injuries, self).save(*args, **kwargs)
            elif Injuries.objects.filter(name=self.name).exists():
                extra = str(randint(1,100))
                self.slug = slugify(str(self.name)) + "-" + extra
                super(Injuries, self).save(*args, **kwargs)
        else:
            if Injuries.objects.filter(name=self.name).exists():
                extra = str(randint(1,100))
                self.slug = slugify(str(self.name)) + "-" + extra
                super(Injuries, self).save(*args, **kwargs)
            else:
                self.slug = slugify(str(self.name))
                super(Injuries, self).save(*args, **kwargs)

injuries/forms.py
from django import forms
from . import models

class AddInjuries(forms.ModelForm):
    class Meta:
        model = models.Injuries
        fields = ['name', 'description', 'symptoms', 'diagnostic_tests', 'classification', 'healing','complications', 'treatment', 'image']
        widgets = {
            
            'description' : forms.Textarea(attrs={'id': 'description', 'class':'materialize-textarea'}),
            'symptoms' : forms.TextInput(attrs={'id': 'symptoms'}),
            'diagnostic_tests' : forms.TextInput(attrs={'id': 'diagnostic_tests'}),
            'complications' : forms.TextInput(attrs={'id': 'complications'}),
            'treatment' : forms.TextInput(attrs={'id': 'treatment'}),
            'healing' : forms.TextInput(attrs={'id': 'healing'}),
            'image' : forms.FileInput(attrs={'id': 'image','type' :'file', 'class' : 'dropify', 'data-height':'100'}),
        }

injuries/views.py
from django.shortcuts import render, redirect
from . models import Injuries
from django.http import HttpResponse
from django.contrib import messages
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from .decorators import admin_required
from . import forms
from players.models import Player
import pandas as pd

# Create your views here.
@login_required(login_url="/account/login/")
def injury_view(request):
    injuries = Injuries.objects.all().order_by('date')
    return render(request, 'injuries/view_injuries.html', {'injuries':injuries})

@login_required(login_url="/account/login/")
def single_injuries(request, slug):
    injury = Injuries.objects.get(slug=slug)
    return render(request, 'injuries/single_injuries.html', {'injury':injury})

@admin_required
@login_required(login_url="/account/login/")
def add_injuries(request):
    if request.method == 'POST':
        form = forms.AddInjuries(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            messages.success(request, 'Injury added successfully!!!')
            return redirect('injuries:add_injury')
        else:
            messages.warning(request, 'Please correct the error below.') 
    else:
        form = forms.AddInjuries()
    return render(request, 'injuries/add_injuries.html', {'form':form})

@login_required(login_url="/account/login/")
@admin_required
def edit_injury(request, slug):
    players = Injuries.objects.get(slug=slug)
    form = forms.AddInjuries(instance=players)
    if request.method == 'POST':
        form = forms.AddInjuries(request.POST, instance=players)
        if form.is_valid():
            form.save()
            messages.success(request, 'Injury information changed successfully!!!')
        else:
            messages.warning(request, 'Please correct the error below.') 
    return render(request, 'injuries/edit_injuries.html', {'form':form})

@login_required(login_url="/account/login/")
def view_players(request):
    players = Player.objects.all()
    return render(request, 'injuries/view_players.html', {'players':players})

@login_required(login_url="/account/login/")
def predict_injury(request, slug):
    age = Player.objects.get(slug=slug).age
    weight = Player.objects.get(slug=slug).weight
    height = Player.objects.get(slug=slug).height
    players = Player.objects.get(slug=slug) #or any kind of queryset

    # Unpickle model 
    model = pd.read_pickle(r'c:\Users\Divine\Downloads\Compressed\YT-Django-Iris-App-3xj9B0qqps-master\new_model.pickle') 
    # read a pickle pd.read_pickle('model.pkl')
    #Make Prediction
    result = model.predict([[age,weight,height]])  # input must be 2D array

    classification = result[0]

    context = {'player':players, 'classification':classification}
    return render(request, 'injuries/predictions.html', context=context)

@login_required(login_url="/account/login/")
@admin_required
def delete_injury(request, id):
    p = Injuries.objects.get(pk=id)
    p.delete()
    return redirect('injuries:view_injuries')

injuries/templates/injuries/add_injuries.html
{% extends 'base_layout.html' %}

{% block content %}
<title>PhysioBoost Admin: Add Player </title>
<section id="content">

    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Add Injury</h5>
            <ol class="breadcrumbs">
              <li><a href="index.html">Dashboard</a>
              </li>
              <li><a href="#">Injuries</a>
              </li>
              <li class="active">Add Injury</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--start container-->
    <div class="container">
      <div class="section">
        <!--Input fields-->
        <div id="input-fields">
          <div class="row">
            <div class="col s12 m8 l12">
              <div class="row">
                <form class="col s12" action="{% url 'injuries:add_injury' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.name }}
                        {{ form.name.errors }}
                      <label for="injury_name">Injury Name</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.description }}
                        {{ form.description.errors }}
                        <label for="description">Description</label>
                    </div>
                  </div><br>
                  
                  <div class="row">
                    <div id="input-date-picker" class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.symptoms }}
                        {{ form.symptoms.errors }}
                        <label for="symptoms">Symptoms</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.diagnostic_tests }}
                        {{ form.diagnostic_tests.errors }}
                      <label for="diagnostic_tests">Diagnostic Tests</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                      <i class="mdi-action-account-circle prefix"></i>
                      {{ form.healing }}
                      {{ form.healing.errors }}
                    <label for="healing">Healing</label>
                  </div>
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.classification }}
                        {{ form.symptoms.errors }}
                        <label for="severity">Severity</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                      <i class="mdi-action-account-circle prefix"></i>
                      {{ form.complications }}
                      {{ form.complications.errors }}
                    <label for="complications">Complications</label>
                  </div>
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.treatment }}
                        {{ form.treatment.errors }}
                        <label for="treatment">Treatment</label>
                    </div>
                  </div><br>
                  <div class="row">
                    <div class="input-field col s12">
                      <p>Upload an Image</p>
                      {{ form.image }}
                      {{ form.image.errors }}
                  </div>
                  </div><br>

                  <div class="center">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Add Injury</button>
                  </div><br>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="divider"></div>
        <!-- Floating Action Button -->
</div>
<!--end container-->

</section>
<!-- END CONTENT -->

{% endblock %}

injuries/templates/injuries/edit_injuries.html
{% extends 'base_layout.html' %}

{% block content %}
<title>PhysioBoost Admin: Edit Injury </title>
<section id="content">

    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">Edit Injury</h5>
            <ol class="breadcrumbs">
              <li><a href="index.html">Dashboard</a>
              </li>
              <li><a href="#">Injuries</a>
              </li>
              <li class="active">Edit Injury</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--start container-->
    <div class="container">
      <div class="section">
        <!--Input fields-->
        <div id="input-fields">
          <div class="row">
            <div class="col s12 m8 l12">
              <div class="row">
                <form class="col s12" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                  <div class="row">
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.name }}
                        {{ form.name.errors }}
                      <label for="injury_name">Injury Name</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.description }}
                        {{ form.description.errors }}
                        <label for="description">Description</label>
                    </div>
                  </div><br>
                  
                  <div class="row">
                    <div id="input-date-picker" class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.symptoms }}
                        {{ form.symptoms.errors }}
                        <label for="symptoms">Symptoms</label>
                    </div>
                    <div class="input-field col s6">
                        <i class="mdi-action-account-circle prefix"></i>
                        {{ form.diagnostic_tests }}
                        {{ form.diagnostic_tests.errors }}
                      <label for="diagnostic_tests">Diagnostic Tests</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                      <i class="mdi-action-account-circle prefix"></i>
                      {{ form.healing }}
                      {{ form.healing.errors }}
                    <label for="healing">Healing</label>
                  </div>
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.classification }}
                        {{ form.symptoms.errors }}
                        <label for="severity">Severity</label>
                    </div>
                  </div><br>

                  <div class="row">
                    <div class="input-field col s6">
                      <i class="mdi-action-account-circle prefix"></i>
                      {{ form.complications }}
                      {{ form.complications.errors }}
                    <label for="complications">Complications</label>
                  </div>
                    <div class="input-field col s6">
                        <i class="mdi-editor-insert-invitation prefix"></i>
                        {{ form.treatment }}
                        {{ form.treatment.errors }}
                        <label for="treatment">Treatment</label>
                    </div>
                  </div><br>
                  <div class="row">
                    <div class="input-field col s12">
                      <p>Upload an Image</p>
                      {{ form.image }}
                      {{ form.image.errors }}
                  </div>
                  </div><br>

                  <div class="center">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Edit Injury</button>
                  </div><br>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="divider"></div>
        <!-- Floating Action Button -->
</div>
<!--end container-->

</section>
<!-- END CONTENT -->

{% endblock %}

injuries/templates/injuries/injuries.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Injuries</h1>
{% endblock %}

injuries/templates/injuries/view_injuries.html
{% extends 'base_layout.html' %}

{% block content %}

<title>PhysioBoost: View injuries</title>
 <!-- START CONTENT -->
 <section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">View injuries</h5>
            <ol class="breadcrumbs">
                <li><a href="index.html">Dashboard</a></li>
                <li><a href="#">Injuries</a></li>
                <li class="active">View injuries</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
    

    <!--start container-->
    <div class="container">
      <div class="section">
        <!--DataTables example-->
        <div id="table-datatables">
          <div class="row">
            
            <div class="col s12 m8 l12">
              <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Symptoms</th>
                        <th>Diagnostic Tests</th>
                        <th>Healing</th>
                        <th>Severity</th>
                        <th>Complications</th>
                        <th>Treatment</th>
                        {% if user.is_authenticated and user.is_admin %}
                        <th>Action</th>
                        {% endif %}
                    </tr>
                </thead>
             
                <tbody>
                    {% for injury in injuries %}
                    <tr>
                        <td><a href="{% url 'injuries:single_injuries' slug=injury.slug %}">{{ injury.name}} </a></td>
                        <td>{{ injury.description }}</td>
                        <td>{{ injury.symptoms }}</td>
                        <td>{{ injury.diagnostic_tests }}</td>
                        <td>{{ injury.healing }}</td>
                        <td class="{{ injury.classification|cut:' ' }}">{{ injury.classification }}</td>
                        <td>{{ injury.complications }}</td>
                        <td>{{ injury.treatment }}</td>
                        {% if user.is_authenticated and user.is_admin %}
                        <td><a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit Injury" href="{% url 'injuries:edit_injuries' slug=injury.slug %}"><i class="mdi-image-edit"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Delete Injury" onclick="return confirm('Are you sure you want to delete this injury? This action cannot be undone');" href="{% url 'injuries:delete_injuries' id=injury.id %}"><i class="mdi-action-delete"></i></a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div> 
        <br>
      </div>
      <!-- Floating Action Button -->
        <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
            <a class="btn-floating btn-large">
              <i class="mdi-action-stars"></i>
            </a>
            <ul>
              <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
              <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
              <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
              <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
            </ul>
        </div>
        <!-- Floating Action Button -->
        
    </div>
    <!--end container-->

  </section>
  <!-- END CONTENT -->
{% endblock %}

injuries/templates/injuries/view_players.html
{% extends 'base_layout.html' %}

{% block content %}

<title>PhysioBoost: View Injury Prediction</title>
 <!-- START CONTENT -->
 <section id="content">
        
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="breadcrumbs-title">View Injury Prediction</h5>
            <ol class="breadcrumbs">
                <li><a href="index.html">Dashboard</a></li>
                <li><a href="#">Injuries</a></li>
                <li class="active">View Injury Prediction</li>
            </ol>
            {% for message in messages %}
            <div id="card-alert" class="card {{ message.tags }}">
                <div class="card-content white-text">
                  <p>{{ message }}</p>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
          </div>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->
    

    <!--start container-->
    <div class="container">
      <div class="section">
        <!--DataTables example-->
        <div id="table-datatables">
          <div class="row">
            
            <div class="col s12 m8 l12">
              <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name & Surname</th>
                        <th>Age</th>
                        <th>Club</th>
                        <th>Height</th>
                        <th>Weight</th>
                        <th>Preferred Foot</th>
                        <th>Position</th>
                        <th style="width: 5%;">Jersey Number</th>
                        <th>Status</th>
                        {% if user.is_authenticated and user.is_admin %}
                        <th>Action</th>
                        {% endif %}
                    </tr>
                </thead>
             
                <tbody>
                    {% for player in players %}
                    <tr>
                        <td><a href="{% url 'players:profile' slug=player.slug %}">{{ player.name}} {{player.surname}}</a></td>
                        <td>{{ player.age }}</td>
                        <td>{{ player.club }}</td>
                        <td>{{ player.height }}</td>
                        <td>{{ player.weight }}</td>
                        <td>{{ player.preferred_foot }}</td>
                        <td>{{ player.position }}</td>
                        <td>{{ player.jersey_number }}</td>
                        <td>{{ player.status }}</td>
                        {% if user.is_authenticated and user.is_admin %}
                        <td><a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="View Injury Prediction" href="{% url 'injuries:predict_injury' slug=player.slug %}"><i class="mdi-action-assignment-returned
                          "></i></a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div> 
        <br>
      </div>
      <!-- Floating Action Button -->
        <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
            <a class="btn-floating btn-large">
              <i class="mdi-action-stars"></i>
            </a>
            <ul>
              <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
              <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
              <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
              <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
            </ul>
        </div>
        <!-- Floating Action Button -->
        
    </div>
    <!--end container-->

  </section>
  <!-- END CONTENT -->
{% endblock %}