articles/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_details, name="details"),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.pay, name="home"),
    url(r'^done/$', views.payment_done, name="done"),
    url(r'^canceled/$', views.payment_canceled, name="canceled"),

]

physioboost/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from account import views as do_login
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^leagues/', include('leagues.urls')),
    url(r'^clubs/', include('clubs.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^injuries/', include('injuries.urls')),
    url(r'^assessment/', include('assessment.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^status/', include('status.urls')),
    url(r'^about/$', views.about),
    url(r'^$', do_login.login_view, name="home"),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name='account/reset-password.html'), name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='account/reset-password-done.html'), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z].+)/$', PasswordResetConfirmView.as_view(template_name='account/reset-password-confirm.html'), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='account/reset-password-complete.html'), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

articles/views.py
from django.shortcuts import render, redirect
from . models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_details(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url="/account/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user.id
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<title>Dashboard</title>
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Add Category</h4>
                        <ol class="breadcrumb p-0 m-0">
                            <li>
                                <a href="#">Admin</a>
                            </li>
                            <li>
                                <a href="#">Category </a>
                            </li>
                            <li class="active">
                                Add Category
                            </li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
<div class="create-article\">
    <h2>Create an Awesome New Article</h2>
    <form action="{% url 'articles:create' %}" class="site-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content%}

<div class="article-detail">
    <div class="article">
        <img src="{{article.thumb.url}}" alt="">
        <h2>{{article.title}}</h2>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>
</div>
{% endblock%}

articles/templates/articles/article_list.html
{%extends 'base_layout.html' %}

{%block content%}
    <h1>Article List</h1>
    <div class="articles">
        {% for article in articles%}
            <div class="article">
                <h2><a href="{% url 'articles:details' slug=article.slug %}">{{ article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
                <p class="author">added by {{article.author.username}}</p>
            </div>
        {% endfor %}
    </div>
{%endblock%}